title: Kurt Kehren
tagline: Mechanical Engineer
logo: mug.PNG

description: |
  <div class="contact-card">
    <a href="https://www.linkedin.com/in/kurtwkehren/" target="_blank" class="btn linkedin">
      <i class="fab fa-linkedin"></i> LinkedIn
    </a>

    <a href="/resume.pdf" target="_blank" class="btn resume">
      <i class="fas fa-file-alt"></i> Resume
    </a>
  </div>

show_downloads: false
theme: jekyll-theme-minimal

head: |
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
